version: '3'
services:

  blade-nginx:
    image: nginx:stable-alpine-perl
    hostname: "blade-nginx"
    ports:
    - 88:88
    volumes:
    - /docker/nginx/gateway/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    restart: always
    networks:
    - blade_net

  web-nginx:
    image: nginx:stable-alpine-perl
    hostname: "web-nginx"
    ports:
      - 8000:8000
    volumes:
      - /docker/nginx/web/html:/usr/share/nginx/html
      - /docker/nginx/web/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    restart: always
    networks:
      - blade_net

  blade-redis:
    image: redis:5.0.2-alpine
    hostname: "blade-redis"
    ports:
    - "3379:6379"
    volumes:
    - /docker/redis/data:/data
    command: "redis-server --appendonly yes"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-admin:
    image: "${REGISTER}/blade-admin:${TAG}"
    ports:
    - 7002:7002
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-gateway1:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.81

  blade-gateway2:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.82

  blade-gateway3:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.83

  blade-auth:
    image: "${REGISTER}/blade-auth:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-log:
    image: "${REGISTER}/blade-log:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-desk:
    image: "${REGISTER}/blade-desk:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-user:
    image: "${REGISTER}/blade-user:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-system:
    image: "${REGISTER}/blade-system:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

networks:
  blade_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/16
