version: '3'
services:

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
    networks:
      blade_net:
        ipv4_address: 172.30.0.48
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure

  sentinel:
    container_name: sentinel
    image: bladex/sentinel-dashboard:1.4.2
    ports:
      - 8858:8858
    restart: on-failure
    networks:
      blade_net:
        ipv4_address: 172.30.0.58

  blade-nginx:
    image: nginx:stable-alpine-perl
    hostname: "blade-nginx"
    ports:
    - 88:88
    volumes:
    - /docker/nginx/gateway/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    restart: always
    networks:
    - blade_net

  web-nginx:
    image: nginx:stable-alpine-perl
    hostname: "web-nginx"
    ports:
      - 8000:8000
    volumes:
      - /docker/nginx/web/html:/usr/share/nginx/html
      - /docker/nginx/web/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    restart: always
    networks:
      - blade_net

  blade-redis:
    image: redis:5.0.2-alpine
    hostname: "blade-redis"
    ports:
    - 3379:6379
    volumes:
    - /docker/redis/data:/data
    command: "redis-server --appendonly yes"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-admin:
    image: "${REGISTER}/blade-admin:${TAG}"
    ports:
    - 7002:7002
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-gateway1:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.81

  blade-gateway2:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.82

  blade-gateway3:
    image: "${REGISTER}/blade-gateway:${TAG}"
    privileged: true
    restart: always
    networks:
      blade_net:
        ipv4_address: 172.30.0.83

  blade-auth:
    image: "${REGISTER}/blade-auth:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-log:
    image: "${REGISTER}/blade-log:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-desk:
    image: "${REGISTER}/blade-desk:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-user:
    image: "${REGISTER}/blade-user:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

  blade-system:
    image: "${REGISTER}/blade-system:${TAG}"
    privileged: true
    restart: always
    networks:
    - blade_net

networks:
  blade_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/16
