ALTER TABLE "BLADE_WF_DEPLOYMENT_FORM"
    ADD ("APP_CONTENT" NCLOB);

COMMENT ON COLUMN "BLADE_WF_DEPLOYMENT_FORM"."APP_CONTENT" IS 'app表单内容';

ALTER TABLE "BLADE_WF_FORM"
    ADD ("APP_CONTENT" NCLOB);

COMMENT ON COLUMN "BLADE_WF_FORM"."APP_CONTENT" IS 'app表单内容';

ALTER TABLE "BLADE_WF_FORM_HISTORY"
    ADD ("APP_CONTENT" NCLOB);

COMMENT ON COLUMN "BLADE_WF_FORM_HISTORY"."APP_CONTENT" IS 'app表单内容';
