ALTER TABLE "BLADE_WF_FORM" ADD ("CATEGORY_ID" NUMBER(20,0));
ALTER TABLE "BLADE_WF_FORM_HISTORY" ADD ("CATEGORY_ID" NUMBER(20,0));
ALTER TABLE "ACT_DE_MODEL" ADD ("CATEGORY_ID" NUMBER(20,0));
ALTER TABLE "ACT_DE_MODEL_HISTORY" ADD ("CATEGORY_ID" NUMBER(20,0));

COMMENT ON COLUMN "BLADE_WF_FORM"."CATEGORY_ID" IS '流程id';
COMMENT ON COLUMN "BLADE_WF_FORM_HISTORY"."CATEGORY_ID" IS '流程id';
COMMENT ON COLUMN "ACT_DE_MODEL"."CATEGORY_ID" IS '流程id';
COMMENT ON COLUMN "ACT_DE_MODEL_HISTORY"."CATEGORY_ID" IS '流程id';
